#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define MANIFEST 24
#define IDR_MYMENU 101
#define IDI_MYICON 201

#define ID_FILE_OPEN 9000
#define ID_FILE_EXIT 9001
#define ID_STUFF_PP 9002
#define ID_STUFF_STOP 9003

#endif // RESOURCE_H_INCLUDED
